<a href="https://colab.research.google.com/github/Skylee0310/KDT_PYTHON/blob/main/11_Colab/20240616_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
# 문제 1- Titanic 데이터셋의 승선한 사람들의 클래스와 성별 10개를 나이가 많은 순서로 나열하여 데이터 프레임 형태로 출력하시오.
top10 = df.sort_values(by='age', ascending =False).head(10)

In [6]:
result = top10[['class', 'sex']]

In [7]:
result

      class   sex
630   First  male
851   Third  male
493   First  male
96    First  male
116   Third  male
672  Second  male
745   First  male
33   Second  male
54    First  male
280   Third  male

In [ ]:
# 문제 2 - Age의 결측값을 평균으로 채우고 Age를 표준정규분포로 스케일링한 값을 Age_scale 열에 저장하시오. 답안은 print(df['Age_scale'])의 형태로 출력하시오.

In [8]:
df['age'].isna().sum()

177

In [9]:
mean_age = df['age'].mean()
df['age'].fillna(mean_age, inplace=True)

In [10]:
df['age'].isna().sum()

0

In [11]:
from sklearn.preprocessing import StandardScaler
sScaler = StandardScaler()
df['Age_scale'] = sScaler.fit_transform(df[['age']])
print(df['Age_scale'])

0     -0.592481
1      0.638789
2     -0.284663
3      0.407926
4      0.407926
         ...
886   -0.207709
887   -0.823344
888    0.000000
889   -0.284663
890    0.177063
Name: Age_scale, Length: 891, dtype: float64

In [12]:
# 문제 3 - 연령대가 30대인 데이터를 추출하여 그 추출된 데이터 중에서 생존한 사람들의 'pclass','sex','age', 'sibsp' 데이터를 데이터프레임 형태로 상위 5개 나타내시오.

In [15]:
mask = (df['age']>=30) & (df['age']<40)

In [20]:
age30 = df[mask]
age30

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,Age_scale
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0.638789
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0.407926
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.407926
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False,0.715743
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False,0.100109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True,0.100109
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True,0.254017
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True,0.254017
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False,0.715743
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.177063

In [22]:
survived_age30 = age30[age30['survived']== 1]  # 괄호 잘 확인하기

In [23]:
survived_age30[['pclass', 'sex', 'age', 'sibsp']].head(5)

    pclass     sex   age  sibsp
1        1  female  38.0      1
3        1  female  35.0      1
21       2    male  34.0      0
25       3  female  38.0      1
61       1  female  38.0      0

In [24]:
# 문제 4 - 생존한 사람과 생존하지 않은 사람들의 나이의 평균값을 순서대로 소수점 둘째 자리까지 구하시오. 단, 나이의 결측값은 전체 탑승자의 평균으로 채우시오.

In [26]:
df['age'].isna().sum()

0

In [28]:
survived = df[df['survived']==1]
not_survived = df[df['survived']==0]

In [29]:
survived_mean = survived['age'].mean()
not_survived_mean = not_survived['age'].mean()

In [36]:
print('생존자 나이 평균값 : ', survived_mean.round(2), '\n사망자 나이 평균값 : ', not_survived_mean.round(2))

생존자 나이 평균값 :  28.55
사망자 나이 평균값 :  30.42

In [38]:
print('생존자 나이 평균값 : ', round(survived_mean, 2), '\n사망자 나이 평균값 : ', round(not_survived_mean, 2))

생존자 나이 평균값 :  28.55
사망자 나이 평균값 :  30.42

In [40]:
# 문제 5 - 요금(Fare)의 최고와 최저 평균을 구하시오.
fare = df['fare']

In [42]:
maxFare = fare.max()
minFare = fare.min()
meanFare = (maxFare+minFare)/2

In [43]:
print(meanFare)

256.1646

In [44]:
# 문제 6 - 생존자 데이터 중 Pclass가 2보다 큰 승객의 Pclass, 나이, 성별을 데이터 프레임 형태로 출력하세요.

In [47]:
survived = df[df['survived']==1]

In [48]:
mask = survived['pclass']>2

In [49]:
survived2 = survived[mask]

In [51]:
result = survived2[['pclass', 'age', 'sex']]
result

     pclass        age     sex
2         3  26.000000  female
8         3  27.000000  female
10        3   4.000000  female
19        3  29.699118  female
22        3  15.000000  female
..      ...        ...     ...
838       3  32.000000    male
855       3  18.000000  female
858       3  24.000000  female
869       3   4.000000    male
875       3  15.000000  female

[119 rows x 3 columns]